version: '3.8'

services:
  api:
    build:
      context: ./server
    env_file:
      - .env.development
    ports:
      - "3001:3001"

  web:
    build:
      context: ./analyzemybill
    env_file:
      - .env.development
    ports:
      - "3000:80"
    depends_on:
      - api
